### PR TITLE
Internationalized and fixed cities names

### PR DESCRIPTION
**Pull request by Wishnia**
It's finally done :smile:

### CODE REVIEW

**Comment by Wishnia** [comment]
CI is reporting some error, but I totally don't understand it. Could you help me?

**Comment by szabgab** [comment]
So the test failure comes because of the Göteborg => Gothenburg. The test was checking if the character transliteration of ö works properly in web addresses as well. Before I update the test I'd like to understand why do you think writing Gothenburg is the preferable way? Does that mean we'll get rid of all the non ascii characters in the city names? eg. Will Malmö also change?

**Comment by Wishnia** [comment]
I changed Göteborg to Gothenburg, because Gothenburg is used internationally and Göteborg is used locally in Sweden. But Malmö city name is both - international and local.
There is lots of cases when cities names are internationalized (like Gothenburg in Sweden or Warsaw in Poland), but some cities names aren't internationalized and we need to them originally (like Malmö).

**Comment by szabgab** [comment]
OK, I've merged it and replaced the failing, and now irrelevant test.

**Pull request merged**
