### PR TITLE
add open fintech 2018, 2019 and oracle openworld 2019 

### PR DESCRIPTION
**Pull request by studiozandra**
#422  adds open fintech 2018, 2019 and oracle openworld2019 JSONs

### CODE REVIEW

**Comment by studiozandra** [comment]
My first PR! Seems I should also remove these from missing_events.md !

**Comment by szabgab** [comment]
Please check the details o the Travis-CI tests. It has helpful error messages as to what needs to be fixed before the PR can be accepted.

**Comment by studiozandra** [comment]
Thanks for your help! I didn't notice the extra messages under "details" and had been Googling "travis ci python no enviroment variables set"  LOL (^_^  )

**Comment by szabgab** [comment]
:smile:

**Comment by szabgab** [comment]
https://codeandtalk.com/e/open-fintech-2018
https://codeandtalk.com/e/open-fintech-2019
https://codeandtalk.com/e/oracle-openworld2019

The last one would be better if it was
https://codeandtalk.com/e/oracle-openworld-2019
would you like to submit a separate pr renaming the file?

**Comment by studiozandra** [comment]
Ok! Will do!!

**Pull request merged**
