### PR TITLE
Add GRCon18 (gnuradio conference)

### PR DESCRIPTION
**Pull request by laf0rge**

### CODE REVIEW

**Comment by rollandf** [comment]
Check the Travis for the errors.
You can also check locally before pushing by running generate.py. (See in the README)

Also, I see there is a COC in the site, it should be also in the JSON:
https://gnuradio.org/grcon-2018/about/code-of-conduct/

**Comment by laf0rge** [comment]
thanks, fixed the errors and added COC, should be fine now.

**Comment by rollandf** [comment]
Great!
Thanks :+1:

**Comment by szabgab** [comment]
Thank you! It is now live at https://codeandtalk.com/e/grcon-2018

**Pull request merged**
