### PR TITLE
I added the Spring CUE 2018 event. Issue #412

### PR DESCRIPTION
**Pull request by jppcel**
Issue #412 .

### CODE REVIEW

**Comment by szabgab** [comment]
Thanks, but it seems the automatic tests report a problem with this change. Please check the "Details" link on this page and look for ERROR.

**Comment by jppcel** [comment]
Yay! It works!

**Comment by szabgab** [comment]
Excellent! Thank you!

Posted here: https://codeandtalk.com/e/spring-cue-2018

**Comment by szabgab** [comment]
Hi, if you sent this in PR because of the Hacktoberfest, there are 3 more days left. Please, tell you friends there are plenty more PR opportunities here. In 3 days they can get a cool T-shirt as well. Please tweet about it mentioning the web site https://codeandtalk.com/ and referencing me @szabgab so I can easily reshare. - Thanks

**Pull request merged**
