### PR TITLE
Updated events & locations

### PR DESCRIPTION
**Pull request by Wishnia**
Added data/events:
- WordCamp Kuala Lumpur 2018 event
- WordCamp Harare 2018 event
- WordCamp Kampala 2018 event
- WordCamp Nairobi 2018 event
- WordCamp Pokhara 2018 event
- WordCamp Sofia 2018 event - please, check "code of conduct" property (event's site is bilingual), there are 2 values and I'm not quite sure if I added it correctly
- WordCamp Montevideo 2018 event
- WordCamp Toronto 2018 event - please, check "hashtag" property, there are 2 values (they have 2 hashtags) and I'm not quite sure if I added it correctly.

Added locations:
- Uganda/Kampala
- Nepal/Pokhara

Fixed:
- A typo in locations: Morocoo -> Morocco
- Typos in data/events: Devoxx Morocco 2016 & Devoxx Morocco 2017

### CODE REVIEW

**Comment by Wishnia** [comment]
Please, look at Travis CI report, it doesn't refer to files I created or changed, so I don't know what to do to fix it.

**Comment by szabgab** [comment]
There is a merge conflict. I'll handle it manually. Please wait with the next PR till I finish it and then update your clone with the new version before making further changes.

**Comment by Wishnia** [comment]
I checked WordCamp Sofia 2018 event page on codeandtalk.com and after clicking "Code of Conduct" it's displaying 404 error - I wrote in PR description that WordCamp's site is bilingual and they have two codes of conduct (so I added both), but I wasn't sure if I added it correctly.

In case of WordCamp Toronto event, they have two hashtags, but codeandtalk.com is ignoring second hashtag.

**Comment by szabgab** [comment]
Thanks for checking.

The codeandtalk system only supports a single hashtag and a single code of conduct link. Neither was properly verified earlier and thus one crashed the check (that you saw earlier) the other just passed and displayed an incorrect link (the code of conduct). I added tests for both cases now and removed one of the hashtags and one of the links to code of conduct.

Thanks again for checking and reporting the issues.

**Pull request merged**
