### PR TITLE
Add new event in Senegal

### PR DESCRIPTION
**Pull request by jkubkub**

### CODE REVIEW

**Comment by jkubkub** [comment]
Same problem . how  can we fix it?

**Comment by szabgab** [comment]
Now you need to add it to `data/locations.json`

**Comment by jkubkub** [comment]
Constantly had error  - 'inappropriate' tag, even with 'Java' tag , so i deleted all of them.

**Comment by szabgab** [comment]
Thanks. It is posted now here: https://codeandtalk.com/e/voxxeddakar-sen-2016
I'll improve the error message of the tags, but in a nutshell tags are all lowercase.

**Pull request merged**
