### PR TITLE
Fix title name duplication 

### PR DESCRIPTION
**Pull request by adityatandon007**
In continuation to #440 
@szabgab

### CODE REVIEW

**Comment by adityatandon007** [comment]
@szabgab fixed and thanks for merging my contribution

**Comment by adityatandon007** [comment]
@szabgab the page doesn't look pretty. I was talking about the url you shared in my earlier PR you just merged few minutes. If there is some html, CSS thing that you need help with I would love to try some of my magic css.

**Comment by szabgab** [comment]
Help with design would be awesome! The README file should provide you with instructions on how to set up the web application on your computer. That will probably make it easier for you to tweak the HTML and the CSS and see the results.

**Comment by szabgab** [comment]
Hi, if you sent this in PR because of the Hacktoberfest, there are 3 more days left. Please, tell you friends there are plenty more PR opportunities here. In 3 days they can get a cool T-shirt as well. Please tweet about it mentioning the web site https://codeandtalk.com/ and referencing me @szabgab so I can easily reshare. - Thanks

**Pull request merged**
