### PR TITLE
Update and rename hugo-giraudel.json to kitty-giraudel.json

### PR DESCRIPTION
**Pull request by KittyGiraudel**

### CODE REVIEW

**Comment by szabgab** [comment]
Hi Kitty,

this change alone would break the cross-reference of the data from the file data/videos/frontendconf-ch-2015/hugo-giraudel-3-years-of-purging-sass.json 

One solution would be to change the content of `data/videos/frontendconf-ch-2015/hugo-giraudel-3-years-of-purging-sass.json` to refer to the file holding your new name.

In that opportunity the name of the file could be also changed either to `kitty-giraudel-3-years-of-purging-sass.json` or to `3-years-of-purging-sass.json`.

**Comment by KittyGiraudel** [comment]
Thank you for letting me know! I believe this should be addressed now. :)

**Comment by szabgab** [comment]
thanks. pushed to the web site.

**Comment by KittyGiraudel** [comment]
Thank you!

**Pull request merged**
