### PR TITLE
REdeploy 2018

### PR DESCRIPTION
**Pull request by mary-grace**

### CODE REVIEW

**Comment by mary-grace** [comment]
I'm not sure what to do to fix this so that the checks don't fail :-/ Suggestions?

**Comment by szabgab** [comment]
Thanks for your PR. I am looking into this error.

**Comment by szabgab** [comment]
There was a formatting error in the JSON file that was not properly reported. I've fixed the reporting and then also fixed the JSON file, including the date. It is published here: https://codeandtalk.com/e/redeploy-2018
Please check if it correct.
Thanks again

**Comment by mary-grace** [comment]
lgtm. thanks!
-- 

MARY THENGVALL
707.291.6220
marygrace.community

Community Pulse Podcast
communitypulse.io

**Pull request merged**
