### PR TITLE
ladybug podcast data

### PR DESCRIPTION
**Pull request by TiaIvonne**
add ladybug podcast data

### CODE REVIEW

**Comment by szabgab** [comment]
Thanks, let's see if this title:

Get a <head> start with HTML

will break the site or not :)

**Comment by szabgab** [comment]
That seems to work, but I had to make some adjustments to the names and add the individual files for each person.

This was apparently something the CI system did not catch.
In any case the list is now here: https://codeandtalk.com/s/ladybug 
Please check the names that I did not mess up anything and feel free to add more information for each person to their respective files.

**Comment by TiaIvonne** [comment]
Hi, I made a mistake, two podcast episode has the same name but already fixed it.

**Comment by TiaIvonne** [comment]
And last but not least, the podcast is on Spotify as well.

**Comment by szabgab** [comment]
I saw the Spotify link, I don't think we had that in the code though. Feel free to update it. The code too :smiley:

**Pull request merged**
