### PR TITLE
create debutsav-kochi-2018.json

### PR DESCRIPTION
**Pull request by vmr1532**
created a new event file

### CODE REVIEW

**Comment by szabgab** [comment]
Thanks, could you please check the errors in the cI system and fix the file accordingly?

**Comment by vmr1532** [comment]
cant understand the cl system. can you point out the errors?
i am new to open source

**Comment by szabgab** [comment]
You click on the "Details" link, then on one of the failed build jobs and scroll down to the end where you can see the ERROR messages. The documentation of the project then explains the rules in detail.

**Comment by Beluosa** [comment]
Hey @vmr1532 !

It looks like there are a few small things to correct and you should be good to go:
1) Your hashtag is invalid. You left a username instead of a hashtag. When you put in your hashtag, do not include the #. You could just remove this line.
2) "india" is not in the list. This is a little weird because "India" is in locations.json but maybe it's case sensitive. I would try it listing "India".

**Pull request closed without merging**
