### PR TITLE
Add PNWPHP 2017

### PR DESCRIPTION
**Pull request by cookieguru**
Unrelated, but do you keep copies of older occurrences of the same conference?  This one has been going strong since 2015.

### CODE REVIEW

**Comment by szabgab** [comment]
Thanks.
Yes, old editions of the conferences are also welcome and then they can also have an entry in the data/series.json file.

**Comment by cookieguru** [comment]
@szabgab Thanks.  A `CONTRIBUTING` guide would be great; explaining the relevant files and the allowable "tags" for each file.

**Comment by szabgab** [comment]
See the top of the README file for explanations

**Comment by cookieguru** [comment]
I don't see anything about contributing in the project's main README, but I just grepped through the code and noticed the various files in the `docs` folder and that explains them nicely.

**Comment by szabgab** [comment]
Added the word CONTRIBUTING to the readme. In case that helps.
BTW please see also this effort: https://github.com/afilina/dev-community-data/issues/90

**Pull request merged**
