### PR TITLE
Add new event in Denmark

### PR DESCRIPTION
**Pull request by jkubkub**

### CODE REVIEW

**Comment by jkubkub** [comment]
if 'youtube' in this and this['youtube'] != '' and this['youtube'] != '-':

            #if not re.search(r'^P[a-zA-Z0-9_-]+$', this['youtube']):

            if re.search(r'https?://', this['youtube']):

>               raise Exception("Invalid youtube playlist '{}' in {}".format(this['youtube'], filename))

E               Exception: Invalid youtube playlist 'https://www.youtube.com/channel/UCJXNOMywewNmau4hzAy4LjA' in /home/travis/build/szabgab/codeandtalk.com/data/events/gr8conf-denmark-2017.json

**Comment by jkubkub** [comment]
need to add ****not to conditional expression?

**Comment by szabgab** [comment]
published here: https://codeandtalk.com/e/gr8conf-denmark-2017
thanks

**Comment by jkubkub** [comment]
hi..just checked,found out that format of Videos link on events page is not
right - https://www.youtube.com/playlist?list=UCJXNOMywewNmau4hzAy4LjA . it
is simply doesnt work
it is should be https://www.youtube.com/channel/UCJXNOMywewNmau4hzAy4LjA

**Comment by szabgab** [comment]
Oh that was a channel you added? That should be a playlist. That's why the links goes to playlist. So it would be better to remove that field.

**Pull request merged**
