### PR TITLE
Adds events mentioned in testing minds

### PR DESCRIPTION
**Pull request by adityatandon007**
This Pr addressees the issue mentioned in #432 by @szabgab

### CODE REVIEW

**Comment by adityatandon007** [comment]
@szabgab travis failed probably because I haven't set up environment variable. Will you be able to merge this. If its so I can pick up some more

**Comment by szabgab** [comment]
It failed because one of the events does not have a city.
In addition we call it "Tel Aviv" only. Please fix that too.

**Comment by adityatandon007** [comment]
@szabgab done!

**Comment by szabgab** [comment]
Thanks. I spotted another issue. the website field is a required field. The URL of the website of the event. I have no idea why our tests have not caught that issue.

**Comment by adityatandon007** [comment]
I don't see the website of the event mentioned. Can you specify where to
get that from?

**Comment by szabgab** [comment]
Where did you take the data from?

**Comment by adityatandon007** [comment]
From testing minds events website that you mentioned in the issue. 
A url for one of them [here](https://www.testingmind.com/event/test-automation-summit-singapore/)

**Comment by szabgab** [comment]
Then that url should go to the "website" field.

**Comment by adityatandon007** [comment]
@szabgab done!

**Comment by szabgab** [comment]
Great, then I have another change or two before I can merge :smile:
The event in Israel is already in our "database" as data/events/testingmind-israel-2017.json
So please remove the same event from your PR.

For the other 2 I'd like the filenames to be testingmind-manila-2017 and testingmind-singapore-2017 and please also get the twitter account from data/events/testingmind-israel-2017.json and add it to the other two events.

**Comment by adityatandon007** [comment]
@szabgab changes done as requested

**Comment by szabgab** [comment]
Thanks.

they are posted here:
https://codeandtalk.com/e/testingmind-manila-2017
https://codeandtalk.com/e/testingmind-singapore-2017

It seems the title has a bit of a repetition.

**Comment by adityatandon007** [comment]
@szabgab do you want me to change the title

**Comment by szabgab** [comment]
that would be nice. In a separate branch. After you updated 'main' from 'upstream'

**Comment by adityatandon007** [comment]
On it!

**Pull request merged**
