### PR TITLE
Page layouts

### PR DESCRIPTION
**Pull request by pauljacobson**
I modified individual podcast, event, and similar pages to fix overall layout inconsistencies.

### CODE REVIEW

**Comment by szabgab** [comment]
Was this pushed on the same branch that was already used for the previous PR?
Better start a new branch from the "main" branch for every PR. Now style.css is in conflict.

**Comment by pauljacobson** [comment]
@szabgab Yes, it was the same branch. I only thought about a new branch after I finished all my commits. I'll go through the conflicts and resolve them.

**Comment by pauljacobson** [comment]
@szabgab Ok, I think I resolved the conflict. This is the correct declaration in the CSS:

```
.wrapper__unit {
    flex: 1;
}
```

**Comment by pauljacobson** [comment]
@szabgab Do you need me to do something else with this PR? I resolved the conflict in the stylesheet.

**Comment by szabgab** [comment]
The tests now fail. Could you check please, why?

**Comment by pauljacobson** [comment]
@szabgab They seem to be Python-related issues. I don't know enough to know what the problem is, and how to fix them. Looking at the Travis report, it looks like part of the issue is a Python version problem. You should probably take a look.

**Comment by szabgab** [comment]
Caused by your change? Of course it looks like Python as the tests are written in Python.

It is an error that we are checking if something is on the page and it is not. Specifically we are checking if `<div>Start date: 2009-11-20</div>` is on a page of the "Full Frontal - ffconf 2009" conference.

**Comment by pauljacobson** [comment]
Ok, I'll see if I can figure out what the problem is. ffconf is under "Previous Conferences" and is the first on the list.

**Comment by pauljacobson** [comment]
@szabgab The event details for that conference load in my test build. I can't tell what the tests are actually testing _for_ here and what the expected outcome is? Are the tests looking for specific syntax for the page template HTML? 

I modified the HTML tags in the templates to fix the syntax. Perhaps that threw the tests out?

**Comment by szabgab** [comment]
probably. 
The Travis report shows that the error is in the test_event function
The tests are here:  
https://github.com/szabgab/codeandtalk.com/blob/main/cat/test_cat.py

the test_event function starts here: https://github.com/szabgab/codeandtalk.com/blob/main/cat/test_cat.py#L105

It fetches a page and checks if various HTML elements with their data are on the pages.
If your intention was to change those HTML elements then you also need to update the tests.
The one that fails is check if the Start date is on the page as it was expected earlier.

**Comment by pauljacobson** [comment]
@szabgab I see where the test criteria are. Next question: should I update the test criteria in the same branch? If I do this in a new branch, the tests will fail because they will apply new test criteria to old page template syntax? What do you suggest?

**Comment by szabgab** [comment]
same branch.

Remember, the tests are there to make sure we don't remove something by mistake. So update them if the changes are intentional.

**Comment by pauljacobson** [comment]
@szabgab Ok, I seem to have adjusted the test parameters and the checks have passed. The commits are ready for you to review and process.

**Comment by szabgab** [comment]
Much improved. Thanks!

**Comment by pauljacobson** [comment]
@szabgab You're welcome, and thanks for your help with these issues.

**Pull request merged**
