### PR TITLE
Fix youtube links

### PR DESCRIPTION
**Pull request by studiozandra**
I re-read the notes and fixed the previous YouTube playlist submissions, and added one more event. Also noted the missing_events.md accordingly.

### CODE REVIEW

**Comment by studiozandra** [comment]
Please let me know in case something doesn't look right, and I'll fix.

**Comment by szabgab** [comment]
could you please fix the conflict with the file name change

**Comment by studiozandra** [comment]
😅😅Sorry about that! 🌃😴 hopefully that fixed it.

**Comment by szabgab** [comment]
Excellent. Thank you

**Pull request merged**
