### PR TITLE
Add agile events

### PR DESCRIPTION
**Pull request by wschwab**
#417 Added Agile2018 and XP2018 (also an Agile Alliance event)

### CODE REVIEW

**Comment by wschwab** [comment]
This is a new error for me - do you know why AppVeyor failed?

**Comment by szabgab** [comment]
Thanks for the PR.

It looks like an unrelated issue. e.g. a network outage for Appveyor or PyPI.

On the other hand I think the names of these events should be Agile and XP respectively. Without the year.

**Comment by wschwab** [comment]
Both included the year in their name on their website - it seems like they're yearly, recurring conferences. Should the year still be left off?

**Comment by szabgab** [comment]
yes, because we automatically add the year when we display the event. See https://codeandtalk.com/e/devday-be-2017 and https://github.com/szabgab/codeandtalk.com/blob/main/data/events/devday-be-2017.json

**Comment by szabgab** [comment]
merged, fixed and published at https://codeandtalk.com/e/agilealliance-agile-2018 and https://codeandtalk.com/e/agilealliance-xp-2018
thanks

**Pull request merged**
