### PR TITLE
Elixir & Lonestar Elixir

### PR DESCRIPTION
**Pull request by MLRiain**

### CODE REVIEW

**Comment by szabgab** [comment]
Thanks.

https://codeandtalk.com/e/elixirconf-2018   but not in a series.
https://codeandtalk.com/e/elixirconf-eu-2018

https://codeandtalk.com/e/lonestar-elixir-2018  but the series is not the same name.

**Comment by MLRiain** [comment]
On Sun, Jan 28, 2018 at 1:57 AM, Gabor Szabo <notifications@github.com>
wrote:

> Thanks.
>
> https://codeandtalk.com/e/elixirconf-2018 but not in a series.
>
​I don't see why it's not, what's different that keeps it out of the
series?​

**Comment by szabgab** [comment]
the spelling in the series was different from the one in the data/events filenames.
I've fixed both cases.

**Comment by MLRiain** [comment]
Thanks. I noticed I had misspelled elixir, did you get that? I kept putting
'e' in it, I thought I'd caught them all but I missed one.

**Pull request merged**
