### PR TITLE
Elixirconf 2017

### PR DESCRIPTION
**Pull request by MLRiain**

### CODE REVIEW

**Comment by szabgab** [comment]
https://codeandtalk.com/e/elixirconf-2017

**Comment by MLRiain** [comment]
I wanted to do the rest of this series but it's a difficult one. Is it
alright to use a GitHub repo as the website?

They have not left the past conferences online in a way that I can get the
info quickly, it's scattered around, but I think I can pull it together. It
was just too much to tackle yesterday.

**Comment by szabgab** [comment]
If you feel this is important to collect then sure, use their GitHub repo.

**Comment by MLRiain** [comment]
I would just like to have the series. I think it's only 2014, 5, 6.

Then there's Lonestar ElixirCon and ElixirCon MX, and ElixirCon EU...do you
want me to try to get them all? I could spend several days on Elixir. Maybe
only two or three, I don't know if they're new or if they have history.

**Pull request merged**
