### PR TITLE
Added WordCamp Cape Town 2018

### PR DESCRIPTION
**Pull request by Wishnia**

### CODE REVIEW

**Comment by szabgab** [comment]
Thanks. Please check the error reported by Travis CI and update the PR

**Comment by Wishnia** [comment]
Okay, I fixed errors reported by Travis, but what to do with AppVeyor errors?

**Comment by szabgab** [comment]
Thanks. Forget about the Appveyor errors. I am turning it off for now.

**Comment by szabgab** [comment]
Published at https://codeandtalk.com/e/wordcamp-cape-town-2018
Thank you!

**Pull request merged**
