### PR TITLE
Update various ApacheCon/colocated events

### PR DESCRIPTION
**Pull request by ShaneCurcuru**

### CODE REVIEW

**Comment by ShaneCurcuru** [comment]
Also add most recent Monktoberfest

**Comment by szabgab** [comment]
Thanks for the PR!
According to the automated tests 'flex' is missing from the existing tags. Please add it to `data/tags.json` and let's see if that is the only issue here or not.

**Comment by ShaneCurcuru** [comment]
D'oh, I should have thought of that.

**Comment by szabgab** [comment]
Getting closer. Now the diversitytickes are at odds with the expectations. 😄

**Comment by szabgab** [comment]
thanks

**Comment by szabgab** [comment]
https://codeandtalk.com/e/monktoberfest-2017

**Pull request merged**
