### PR TITLE
Page layouts

### PR DESCRIPTION
**Pull request by pauljacobson**
I edited the basic layouts of the pages to give them all a consistent appearance (blue border, centered on the page).

### CODE REVIEW

**Comment by szabgab** [comment]
thanks. deployed. I think the individual event pages still need the update, right? e.g. https://codeandtalk.com/e/devday-pl-2012

**Comment by rollandf** [comment]
Looks good!!

**Comment by pauljacobson** [comment]
@szabgab Ah, I missed those pages. I'll take a look and fix those too.

**Comment by pauljacobson** [comment]
Just submitted a new pull request.

**Pull request merged**
