### PR TITLE
bangbangcon (!!Con)

### PR DESCRIPTION
**Pull request by MLRiain**

### CODE REVIEW

**Comment by szabgab** [comment]
Looks good, and you also updated the series.json but now we have two entries and two spellings for New York (the city) in the locations.json file. One is "New York" the other one is "New York City". We should have only one.
For now please remove "New York City" and change the files in this PR to have "New York" in them so I can accept this PR.

If you think "New York City" is much better than "New York" then you can change that in both the locations.json file and in all the events/*.json file in a separate PR.

**Comment by MLRiain** [comment]
Using "New York" when you mean the city is wrong. I don't know how to find
all the instances of "New York" as city in the files and change them. Maybe
whoever made those mistakes should correct them.

**Comment by szabgab** [comment]
It might be wrong but I've heard "New York" referring to the city many times, both in movies and in casual conversation with Americans. So when I started to collect the data I used that and since then everyone accepted it.

In addition we, in an Open Source project cannot expect past contributors to come and make changes, even if they are mistakes. They were and they are volunteers.
What we can do is to fix mistakes (if they are really mistakes) in the project as it is now.

We already have a few places where the came city appears in multiple spellings. We would like to fix those #478 not increase their number.
So I'd still like you to change the name in your PR to "New York".
Then as you don't know how to find all the occurrences (A script would be needed for that.) Then please add a specific comment to #478 asking to rename "New York" (the city) to "New York City".

**Comment by szabgab** [comment]
Thank you for the updates!
https://codeandtalk.com/e/bangbangcon-2017

**Comment by MLRiain** [comment]
Beautiful! Could you put a comma after the city, please?

!!Con sounds like fun, doesn't it?

**Pull request merged**
